### ISSUE TITLE
Unreal Engine Plugin

### ISSUE THREAD

**Issue by charneykaye** [xjmusic/UnrealPlugin#1]
- [x] Plugin function inside a user's Unreal Engine game project
	- [X] Read the exported files from the game resources folder
	- [X] Instantiate the Engine to load the XJ project file
	- [X] Start the work-- this will refresh the content from inside the build folder of the XJ project
	- [X] Start the XJ music engine work with a specific template-- dropdown can read all available templates from the Engine after it loads the project
	- [X] Periodically call the XJ music engine to find out what audio needs to be scheduled or any updates to the audio that is currently playing
		- [X] Schedule playback of an audio file
		- [x] Change volume of an audio file currently playing - Pay attention to the audio schedule event getFromVolume() and getToVolume() and use these to set the volume of the sound. Ideally, we will automate the volume movement so it changes from->to from the beginning of playback of this sound to the end
		- [X] Stop playback of an audio file
		- [X] Consume the new AudioScheduleEvent object to Create/Update/Delete audios playing (instead of repeatedly consuming the entire list)
	- [X] resolve Unreal engine playback termination and/or thread usage problems
	- [x] Unreal Engine loads and prepares all XJ music project audio files during the Unreal project cooking process
	- [x] Enable the Unreal Engine game to send signals to the XJ music engine when there need to be changes in the music
		- [x] Set intensity (float)
		- [X] Set memes (set of strings)
	- [x] XJ mixer output functions as a node inside of the Sound Cue
	- [x] Compatibility with UE5
- [x] How to build & ship plugin
	- [x] Plugin code committed to repository should not duplicate the xjmusic engine code- not the headers nor the .lib, not for the engine nor its dependencies, i.e. spdlog and nlohmann
	- [x] Use a build script to prepare the plugin dependencies
		- [X] build the xjmusic engine .lib
		- [X] copy the xjmusic engine headers into place
		- [X] copy nlohmann where when it's already downloaded
- [x] Unreal Engine interoperates with the XJ music workstation
	- [x] Use clicks the toolbar button in Unreal Engine to open the current Unreal project settings XJ project file in the XJ music workstation - requires xjmusic/xjmusic#463
	- [x] XJ music settings, only necessary to provide path to project file (no project folder setting) and we will compute the path to the project folder, see [Engine.cpp:165](https://github.com/xjmusic/xjmusic/blob/main/engine/src/Engine.cpp#L165) and then [Engine.getPathToBuildDirectory()](https://github.com/xjmusic/xjmusic/blob/main/engine/include/xjmusic/Engine.h#L119)
	- [X] XJ music workstation has a feature to "Build" the project (e.g. compiling a Blueprint inside Unreal before using it) which updates the production template files inside the Unreal project - xjmusic/xjmusic#421 
	- [x] While running the workstation, use the Build feature to export the production template format (one .json file and flat set of converted audio files) to the **build** folder inside the XJ music project folder
	- [X] Configure the XJ music Unreal Plugin inside your game with the location of the XJ music project file in your Unreal project 
	- [x] Plugin shows toolbar in Unreal Engine with an option to launch the XJ music workstation
	- [X] How does the plugin/workstation understand the connection between the original working .xj project (with subfolders for library/program/instrument .json files and their audio files) and the production template that lives in the Unreal Project
- [x] Engine work in C++ xjmusic/xjmusic#401 the last mile of being able to run XJ music production from inside the C++ engine code
- [x] xjmusic/xjmusic#377
- [x] Create folder in main repository containing Unreal Engine plugin files - .uplugin file and sub-folders
- [x] Asset manager extension
	- [x] All audios loaded to the content browser and used by the plugin from there
	- [x] Custom asset type that reference or impersonate xj project
- [x] Set Copyright on all XJ files `Copyright (c) XJ Music Inc. (https://xjmusic.com) All Rights Reserved.`
- [ ] Update repository structure so the root contains the .uplugin file
  - [ ] put the example project in an **Examples** folder
  - [x] Update README instructions / Setup scripts to show user how to setup the example project locally by copying the example project somewhere and then putting the plugin into it
